# Generated by Django 5.1.15 on 2026-02-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
